# Exercises

In [66]:
import numpy as np

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:

# formula = weight / (height**2) * 730
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = ([110, 120, 130, 140, 150, 160, 170])

newHeight = height * height


bmi = weight / (height**2) * 730
print(bmi)

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]




[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [60]:
"""
Example Result for make_matrix(0,15,(3,3)):
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""

def make_matrix(low, high, data_type = np.int32, shape=(3,3)):
    matrix = np.random.uniform(low, high, shape)
    return matrix.astype(data_type)
print(make_matrix(1, 20, np.float64, (4, 4)))

[[ 1.33280992 19.33681292 10.51240461  6.15495652]
 [18.99350199 15.41210756  3.67636761  2.1466058 ]
 [ 1.07454215  9.30392182 15.94150595 13.28314746]
 [10.79074068 18.55159832  4.36707799 13.30975036]]


### #3 - Open and load the data for the Chicago White Sox hitting data for this past season.Create a function that will compare the infield players output vs the outfield players output vs *hybrid. (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - {LF, CF, RF, OF}, *Hybrid - {DH, UT}) for a specific stat. i.e. BA or HR or OPS

*Hybrid is optional


In [65]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [145]:
import csv
import numpy as np

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, filling_values='n/a',
            names=True, dtype = DATATYPES, invalid_raise = False)
    return data

ws = load_data('ws.csv')

def getData(str):
    inFieldPos = 'C', '1B', '2B', 'SS', '3B', 'MI'  
    outFieldPos = 'LF', 'CF', 'RF', 'OF'
    hybridPos = 'DH', 'UT'
    inField = []
    outField = []
    hybrid = []
    
#     Divide the players into their postion

    for player in range(len(ws)):
        position = ws[player][1].decode('utf-8')
        if position in inFieldPos:
            inField.append(ws[player])

    for player in range(len(ws)):
        position = ws[player][1].decode('utf-8')
        if position in outFieldPos:
            outField.append(ws[player])
            
    for player in range(len(ws)):
        position = ws[player][1].decode('utf-8')
        if position in hybridPos:
            hybrid.append(ws[player])
#     --------
    in_total = 0 
    out_total = 0
    hy_total = 0
    
#     Get each Sections average

    for player in range(len(inField)):
        in_total += ws[player][str]
    in_ave = (in_total / len(inField))
    
    for player in range(len(outField)):
        out_total += ws[player][str]
    out_ave = (out_total / len(outField))
    
    for player in range(len(hybrid)):
        hy_total += ws[player][str]
    hy_ave = (hy_total / len(hybrid))
    
#     Decide who has the best Average
    
    if in_ave > out_ave and in_ave > hy_ave:
        return f'Infield has the best Average with {round(in_ave, 3)} vs {round(out_ave, 3)} vs {round(hy_ave, 3)}'
    elif out_ave > in_ave and out_ave > hy_ave:
        return f'Outfield has the best Average with {round(out_ave, 3)} vs {round(in_ave, 3)} vs {round(hy_ave, 3)}'
    elif hy_ave > in_ave and hy_ave > out_ave:
        return f'Hybrid hitters have the best Average {round(hy_ave, 3)} vs {round(out_ave, 3)} vs {round(in_ave, 3)}'
    elif in_ave == out_ave:
        return f'Infield and Outfield hitters have the same best Average {round(in_ave, 3)} vs {round(out_ave, 3)}'
    elif out_ave == hy_ave:
        return f'Hybrid and Outfield hitters have the same best Average {round(hy_ave, 3)} vs {round(out_ave, 3)}'
    elif in_ave == hy_ave:
        return f'Hybrid and Infield hitters have the same best Average {round(hy_ave, 3)} vs {round(in_ave, 3)}'

print("White Sox")
# getData('H')
# getData('OPS')
# getData('HR')
# getData('RBI')S
getData('BA')

White Sox


'Infield has the best Average with 0.262 vs 0.261 vs 0.261'